### ISSUE TITLE
`hotAngular.test(...).module(...).decorator is not a function` error

### ISSUE THREAD

**Issue by altryne** [vitaliy-bobrov/angular-hot-loader#17] opened 2017-05-15 23:11 UTC
Hey,
Thanks so much for doing this! 
Trying to implement according to your README, and getting the error

`hotAngular.test(...).module(...).decorator is not a function`

And not even sure how to go about this, any advice?

**Comment by altryne** [comment] 2017-05-15 23:14
Some context:
Using angular 1.5.8
Webpack 2

**Comment by zalishchuk** [comment] 2017-05-18 00:09
Duplicate of #15, same problem, some interceptors must be rewritten

**Comment by vitaliy-bobrov** [comment] 2017-05-18 21:02
@altryne, decorator wasn't implemented, I've added it in v0.9.5, please try it and let me know if everything going fine.

**Comment by altryne** [comment] 2017-05-19 00:22
@vitaliy-bobrov thanks for the quick feedback. 
Trying again, I now seem to have the following: 

```Cannot read property 'sources' of undefined```
So I assume that this issue can be closed, but I still struggle with trying to get this package to work.

**Comment by vitaliy-bobrov** [comment] 2017-05-19 19:18
@altryne, Need more info to investigate issue.

**Comment by Rendrik** [comment] 2017-06-05 03:05
> Cannot read property 'sources' of undefined

It seems like when logging is enabled, the sources map is accessed before it's defined:
https://github.com/vitaliy-bobrov/angular-hot-loader/blob/master/lib/loader.js#L30
It's defined later @ line 58.  When I got this error, moving the log below the definition in my node_modules worked fine.

**Comment by vitaliy-bobrov** [comment] 2017-06-05 20:03
@Rendrik, updated in v0.9.7

**Closed as completed** 2017-06-26 18:36 UTC
Labels: bug, wait for feedback
